apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-controller
  name: "mongo-controller"
  namespace: "default"
spec:
  replicas: 1
  selector:
    name: mongo-controller
  template:
    metadata:
      labels:
        name: mongo-controller
    spec:
      restartPolicy: Always
      containers:
      - name: mongo
        image: mongo
        command:
        - mongod
        - --storageEngine=wiredTiger
        imagePullPolicy: Always