apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  ports:
  - name: mongocontainer
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongo-controller